# Generated by Django 3.1.7 on 2021-05-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DateApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='reword',
            new_name='reward',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='reword',
            new_name='reward',
        ),
        migrations.RenameField(
            model_name='planhistory',
            old_name='reword',
            new_name='reward',
        ),
    ]
