# Generated by Django 3.1.7 on 2021-05-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DateApp', '0003_auto_20210531_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanHistory',
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='afterChangeRewards',
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='cost',
        ),
    ]
