# Generated by Django 3.1.7 on 2021-05-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DateApp', '0005_changehistory_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changehistory',
            name='buildTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='buildTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='endTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
