# Generated by Django 3.1.7 on 2021-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DateApp', '0006_auto_20210531_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changehistory',
            name='buildTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='buildTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='endTime',
            field=models.DateTimeField(),
        ),
    ]
