# Generated by Django 3.1.7 on 2021-06-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DateApp', '0007_auto_20210531_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
